if(NOT DEFINED LUNAX_SOURCE_DIR)
    get_filename_component(LUNAX_SOURCE_DIR
        "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
if(NOT DEFINED RELEASE_TAG OR NOT RELEASE_TAG MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "RELEASE_TAG must have the form vX.Y.Z")
endif()

file(READ "${LUNAX_SOURCE_DIR}/VERSION" version)
string(STRIP "${version}" version)
file(READ "${LUNAX_SOURCE_DIR}/compatibility/luna.json" compatibility)
string(JSON compatibility_version GET "${compatibility}" lunax_version)
string(JSON luna_language_version GET "${compatibility}" luna language_version)
string(JSON luna_release_tag GET "${compatibility}" luna release_tag)
string(JSON luna_source_commit GET "${compatibility}" luna source_commit)
file(READ "${LUNAX_SOURCE_DIR}/luna.package" package_manifest)
file(READ "${LUNAX_SOURCE_DIR}/CMakeLists.txt" cmake_project)
file(READ "${LUNAX_SOURCE_DIR}/src/commands.luna" commands_source)
file(READ "${LUNAX_SOURCE_DIR}/native/src/Host.cpp" host_source)

if(NOT RELEASE_TAG STREQUAL "v${version}")
    message(FATAL_ERROR "release tag ${RELEASE_TAG} does not match VERSION ${version}")
endif()
if(NOT compatibility_version STREQUAL version)
    message(FATAL_ERROR
        "compatibility version ${compatibility_version} does not match ${version}")
endif()
if(NOT package_manifest MATCHES "version = \"${version}\"")
    message(FATAL_ERROR "luna.package version does not match ${version}")
endif()
if(NOT package_manifest MATCHES "kind = \"application\"")
    message(FATAL_ERROR "luna.package must declare kind = \"application\"")
endif()
if(NOT cmake_project MATCHES
    "project\\(Lunax[ \t\r\n]+VERSION[ \t\r\n]+${version}([ \t\r\n]|\\))")
    message(FATAL_ERROR "CMake project version does not match ${version}")
endif()
if(NOT commands_source MATCHES "Lunax ${version} - Luna ecosystem manager" OR
   NOT commands_source MATCHES "lunax ${version}")
    message(FATAL_ERROR "Lunax CLI version does not match ${version}")
endif()
if(NOT host_source MATCHES "lunax/${version}")
    message(FATAL_ERROR "Lunax HTTP user agent does not match ${version}")
endif()
if(NOT luna_release_tag MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "compatibility Luna release tag is invalid")
endif()
if(NOT luna_release_tag STREQUAL "v${luna_language_version}")
    message(FATAL_ERROR
        "compatibility Luna tag ${luna_release_tag} does not match language version ${luna_language_version}")
endif()
string(LENGTH "${luna_source_commit}" luna_source_commit_length)
if(NOT luna_source_commit_length EQUAL 40 OR
   NOT luna_source_commit MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR
        "compatibility Luna source commit must be a full lowercase 40-hex SHA")
endif()

message(STATUS
    "Lunax ${version} metadata verified against Luna ${luna_release_tag} (${luna_source_commit})")
